---
name: Run-Env
version: 0.03
author:
  - 'Jozef Kutej <jozef@kutej.net>'
abstract: running environment detection
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp::Clan: 0
  File::Spec: 0
  List::MoreUtils: 0
build_requires:
  Test::More: 0
provides:
  Run::Env:
    file: lib/Run/Env.pm
    version: 0.03
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
