---
abstract: 'running environment detection'
author:
  - 'Jozef Kutej <jozef@kutej.net>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Run-Env
provides:
  Run::Env:
    file: lib/Run/Env.pm
    version: 0.04
requires:
  Carp::Clan: 0
  File::Spec: 0
  List::MoreUtils: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
